import Head from 'next/head'
import Footer from '../Component/Footer'
import Navbar from '../Component/Navbar'
import Intro from '../Component/Intro.jsx'
import Services from '../Component/Services'
import { data } from '../../data'
import SignUp from '../Component/SignUp'
import { users } from '../../data'




export default function Home({services}) {
  console.log(services)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      
      <Intro/>
      <Services services={services}/>
      <SignUp/>
      <Footer />
    </div>
  )
}
export const getStaticProps= async ()=>{
  const services=data;
  return{
    props:{services},
  };
}
